name: 'MkDocs Page Publisher'
author: 'Kaijie Yu'
description: |-
  Deploy MkDocs source files as Github Pages. Multi-languages can be
  handled by providing config files.

branding:
  icon: 'globe'
  color: 'white'

inputs:
  config-files:
    description: |-
      Newline-separated list of config files to build.
      e.g.,
        config/en/mkdocs.yml
        config/zh-Hans/mkdocs.yml
      If you don't provide one, mkdocs.yml in the root directory will be used.
    required: false
    default: ''
    type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    container: kjuly/mkdocs-material:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build static pages
        if: inputs.config-files == ''
        run: mkdocs build
      - name: Build static pages with custom config files
        if: inputs.config-files != ''
        run: |
          config_files="${{ inputs.config-files }}"
          IFS=$'\n'
          for config_file in $config_files; do
            echo "- $config_file"
            mkdocs build --config-file "$config_file"
          done
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pages
          path: build
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Upload artifact
        uses: actions/download-artifact@v4
        with:
          name: pages
          path: .
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
